# Generated by Django 4.2.1 on 2023-06-04 14:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patronymic', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('woman', 'Жіноча'), ('man', 'Чоловіча')], max_length=10)),
                ('nationality', models.CharField(choices=[('ukrainian', 'Українська'), ('polish', 'Польська'), ('italian', 'Італійська')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Номер телефону повинен бути у форматі: '+380123456789' або '096-456-78-90' або '0983456789'.", regex='^(\\+\\d{1,2})?[- ]?\\(?(\\d{3})\\)?[- ]?(\\d{3})[- ]?(\\d{2})[- ]?(\\d{2})$')])),
                ('education', models.CharField(choices=[('higher', 'Вища'), ('average', 'Середня'), ('none', 'Немає')], max_length=10)),
                ('activity_field', models.CharField(blank=True, max_length=255)),
                ('hobby', models.TextField(blank=True, max_length=500)),
                ('pets', models.CharField(blank=True, max_length=255)),
                ('favorite_holiday', models.CharField(blank=True, max_length=120)),
                ('favorite_color', models.CharField(blank=True, max_length=120)),
                ('favorite_dish', models.CharField(blank=True, max_length=120)),
                ('favorite_drink', models.CharField(blank=True, max_length=120)),
                ('favorite_musician', models.CharField(blank=True, max_length=120)),
                ('favorite_actor', models.CharField(blank=True, max_length=120)),
                ('favorite_book', models.CharField(blank=True, max_length=120)),
                ('favorite_movie', models.CharField(blank=True, max_length=120)),
                ('appreciate_in_people', models.TextField(blank=True, max_length=500)),
                ('repulsive_in_people', models.TextField(blank=True, max_length=500)),
                ('is_accepted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Учасник клубу',
                'verbose_name_plural': 'Учасники клубу',
                'db_table': 'Club_members',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Області',
                'db_table': 'Regions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.region')),
            ],
            options={
                'verbose_name': 'Населений пункт',
                'verbose_name_plural': 'Населені пункти',
                'db_table': 'Settlements',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MarriedCouple',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_marriage', models.DateField()),
                ('husband', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_as_husband', to='info.clubmember')),
                ('wife', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_as_wife', to='info.clubmember')),
            ],
            options={
                'verbose_name': 'Складена пара',
                'verbose_name_plural': 'Складені пари',
                'db_table': 'Married_couples',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='clubmember',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.settlement'),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
